### PR TITLE
Update Team CodeBender's team page

### PR DESCRIPTION
**Pull request by thngkaiyuan**

### CODE REVIEW

**Comment by thngkaiyuan** [comment]
Do note that the single commit is the "squashed" effort of all my team members, and not just mine :)

**Comment by damithc** [comment]
@lowjoel This one doesn't have any real names?
I'm ok with using Github IDs as primary identifier, but in cases where the github id doesn't contain any hint about the real name, may be we can specify the real name as well? e.g.

# @imadoofus (Daniel)

**Comment by lowjoel** [comment]
OK looks like I need to clarify the templates further, hang on.

**Comment by lowjoel** [comment]
@damithc Have a look at the templates now? I just pushed some changes. Hopefully this is clearer for the other teams who are yet to push their team pages.

**Pull request merged**
