### PR TITLE
fixed markdown formatting issue

### PR DESCRIPTION
**Pull request by AlexLMeow**
~~using '-' for list items requires that there is no '+' in the list item body :(~~

edit: ignore above text

### CODE REVIEW

**Comment by lowjoel** [comment]
What do you mean by no '+'?

**Comment by AlexLMeow** [comment]
No I was mistaken, you can disregard that.

If you look at [the website](http://nus-oss.github.io/cs3281/teams/socketio/) under my (Yijin) contributions, the formatting is messed up. It should be an unordered list but ends up as a paragraph.

I think it's caused by the [line I am removing in this commit](https://github.com/nus-fboa2016-si/cs3281/commit/218ac9ac008ca090e30f7d3955d1913d331709bb). Maybe the parser doesn't accept any extra text before the first ' \* '.

**Comment by lowjoel** [comment]
You can keep the line, just add another empty line after the heading.

**Comment by AlexLMeow** [comment]
ok, done.

**Comment by lowjoel** [comment]
@YijinL seems to have fixed it.

**Comment by AlexLMeow** [comment]
Yup, thanks!

**Pull request merged**
